/**
 * Matt's library, by title, as it stood on 2026-09-26: the names a spoken command has to find its note among
 * (capture/noteFind.ts). With the Guide's chapters, which the recorder leaves out of what a command can name, and
 * two canvases, which it leaves out too.
 */

export const LIBRARY_TITLES: readonly string[] = [
  'A market order is a limit order',
  'Android perf: Sep 10 build vs now',
  'Branches, the PR stack and the team rules',
  'Building a production APK that installs over the store app',
  'Building and shipping HelloTrade',
  'Builds, versions and signing',
  'CI, and the tests that never run',
  'Canvas · From tap to fill',
  'Canvas · The tick path',
  'Claude Rules',
  'Cross margin and isolated margin',
  'Daily Life',
  'Dark mode, typography and translations',
  'Data-layer patterns that keep renders down',
  'Detox end-to-end tests',
  'Every gate in placeOrder',
  'Everything a note can hold',
  'Four ways in',
  'From credential to session',
  'From tap to fill',
  'HelloTrade in one page',
  'HelloTrade — The Book',
  'HelloTrade: Frontend Developer Guide',
  'HelloTrade: The Book',
  'House TODOs',
  'How Glyph is put together',
  'How HelloTrade Flows',
  'How prices reach the screen',
  'How screens read prices',
  'How to format a note',
  "It's post",
  'Leverage, and what it costs you',
  'Liquidation, and the number that matters',
  'Measuring performance',
  'Metro and the dev client',
  'Nightly and local OTA updates',
  'One flush per frame',
  'One socket per channel',
  'Pro Trade performance',
  'Quality gates: qa, jest and what CI actually runs',
  'Questions',
  'RFQ, and the honest part about RWAs',
  'Ramblings ',
  'Signing in, and signing',
  'Signing the order',
  'State splits four ways',
  'Stopping a hidden screen, and the pull side',
  'Subscribed before any screen',
  'Task Management',
  'The Galaxy Fold',
  'The emulator',
  'The execution report',
  'The gates before a commit',
  'The mount chain and the tab shell',
  'The order types, and TP/SL',
  'The repo in one page',
  'The risks, and a glossary',
  'The seventeen sites',
  'The shape of the fix',
  'The standing rules',
  'The three signing shapes',
  "The trade screen's shortcut",
  'The two things you can trade',
  'Three prices, not one',
  'Todo',
  'Trading on HelloTrade',
  'Troubleshooting: symptom to cause',
  'Two forms, one function',
  'Untitled canvas',
  'Variants, stages and build profiles',
  'What the numbers say',
  'Where the docs are wrong',
  'Where the session lives, and how it stays alive',
  'Whoa',
  'Why the position arrives by refetch',
  'hello-kit and the V2 conventions'
];

export const GUIDE_CHAPTER_TITLES: readonly string[] = [
  'The first five minutes',
  'A note is a Markdown file',
  'Finding your way around',
  'The marks you can type',
  'Effects on words',
  'Links between notes',
  'Tags, footnotes and the small marks',
  'Pictures and voice memos',
  'Recording a note',
  'Saying the marks',
  'Commands after Hey Ghost',
  'Lists and to-dos',
  'Boards made of list items',
  'Books, and reading one through',
  'Canvases, cards and lines',
  'The models on your phone',
  'Asking the AI to work on a note',
  'Spoken asks and the review',
  'Accounts, sync and the key you hold',
  'Live typing',
  'Sharing a note or a book',
  'Notion and GitHub',
  'Claude on your notes',
  'Settings, one section at a time',
  'The side key, the Fold and the Mac',
  'What stays on your phone',
  'Ghost.md in one page',
  'No router, five screens',
  'The native half',
  'The editor and its language',
  'Formats that stay Markdown',
  'The plugin seam',
  'From microphone to Markdown',
  'Reading a command, writing it safely',
  'The engines on the device',
  'The library on disk',
  'Sync and the end-to-end keys',
  'Live typing over a relay',
  'glyph-api, the server',
  'The Claude connector, inside',
  'Over the air, and releases',
  'Tests, and the report that ships',
  'Working on Ghost.md',
  'Where the docs and the code disagree'
];
