import { useSyncExternalStore } from 'react';
import type { HapticKind } from '@glacier/react';
import { isNativeMobile } from './platform.ts';

/**
 * The motor, and the rules about when it is allowed to speak.
 *
 * Glyph asks more of haptics than most apps: the other Glacier apps buzz when
 * you press something, which is one event per deliberate act. Here the hand is
 * typing, and the events are generated BY the typing - a mark closing, a
 * heading being born - at whatever rate the thumbs manage. That changes the
 * problem from "fire a taptic" to "decide which keystrokes are worth a taptic
 * and refuse the rest", which is what the floor below is for.
 *
 * WHERE THIS ACTUALLY FIRES. The kit ships web fallbacks (navigator.vibrate,
 * the iOS `<input switch>` trick) and neither reaches WKWebView, so a phone
 * build has to cross the Tauri bridge to `UIFeedbackGenerator` - which is also
 * simply better: real intensity tiers, the selection tick, the notification
 * triplets. A browser tab gets nothing at all, deliberately: `AppProviders`
 * mounts the kit's `HapticsProvider` with `enabled={false}` (see
 * `installTapHaptics` for why) and that same flag gates the kit's web engine.
 */

/** Loaded lazily so a desktop or browser build never pulls the plugin module. */
let pluginPromise: Promise<typeof import('@tauri-apps/plugin-haptics')> | null = null;
function plugin() {
  pluginPromise ??= import('@tauri-apps/plugin-haptics');
  return pluginPromise;
}

/**
 * The kit's seven kinds, spoken in UIFeedbackGenerator's dialect. Impacts map
 * by weight; the three notification kinds are exactly what
 * UINotificationFeedbackGenerator was built to say.
 *
 * The preference is enforced HERE rather than at each call site, because the
 * kit's provider gates its delegated presses on `enabled` but hands a custom
 * impl through `useHaptics` ungated - so this is the one place every path into
 * the motor passes through.
 */
export function fireNativeHaptic(kind: HapticKind = 'light'): void {
  if (!isNativeMobile) return;
  if (!hapticsPref()) return;
  void plugin()
    .then((h) => {
      switch (kind) {
        case 'selection':
          return h.selectionFeedback();
        case 'medium':
          return h.impactFeedback('medium');
        case 'heavy':
          return h.impactFeedback('heavy');
        case 'success':
        case 'warning':
        case 'error':
          return h.notificationFeedback(kind);
        default:
          return h.impactFeedback('light');
      }
    })
    .catch(() => {
      // A bridge that will not buzz is silence, not an error worth surfacing.
    });
}

/**
 * The rate floor, for everything the typing hand can outrun.
 *
 * `fireNativeHaptic` has no limit of its own, which is right for a one-shot: a
 * tap should answer immediately, every time. It is wrong for anything a finger
 * can repeat faster than the engine can speak, and typing is the worst case
 * there is - `**bold**` alone offers several candidate moments inside a second.
 * The Taptic Engine queues a flood and plays it back as mush, so every
 * editor-driven haptic comes through here.
 *
 * 28 ms is AttackFM's measured floor, kept identical on purpose: two apps whose
 * hands disagree feel like two different phones.
 */
const FLOOR_MS = 28;
let lastFireAt = 0;

export function fireFelt(kind: HapticKind = 'light', at = performance.now()): void {
  if (at - lastFireAt < FLOOR_MS) return;
  lastFireAt = at;
  fireNativeHaptic(kind);
}

/**
 * The tier below the kit's seven kinds: UIImpactFeedbackGenerator's `soft`
 * style, the gentlest thing the Taptic Engine says. Texture rather than event -
 * a list continuing itself onto the next line is not news, but it should not
 * be silent either.
 */
export function fireMicroTick(at = performance.now()): void {
  if (!isNativeMobile) return;
  if (!hapticsPref()) return;
  if (at - lastFireAt < FLOOR_MS) return;
  lastFireAt = at;
  void plugin()
    .then((h) => h.impactFeedback('soft'))
    .catch(() => {
      // Silence, as ever.
    });
}

/** The impl handed to the kit's HapticsProvider, or undefined where there is no motor. */
export const hapticsImpl = isNativeMobile ? fireNativeHaptic : undefined;

/**
 * Whether this device has a motor at all. Exported because a switch for
 * something that cannot happen is worse than no switch.
 */
export function hapticsAvailable(): boolean {
  return isNativeMobile;
}

// --- the tap tick ---------------------------------------------------------

/** What counts as something you TAP, and so something that should answer. */
const TAPPABLE =
  'button, a, input, select, label, summary, [role="button"], [role="menuitem"],' +
  ' [role="menuitemradio"], [role="menuitemcheckbox"], [role="tab"], [role="switch"],' +
  ' [role="option"], [role="link"]';

/** How far a finger may travel and still have been a tap rather than a drag. */
const TAP_SLOP_PX = 10;
/** How long it may rest and still be a tap rather than a press-and-hold. */
const TAP_MAX_MS = 700;

/**
 * The app-wide tap tick.
 *
 * The kit ships this as one delegated POINTERDOWN listener, which is why it is
 * switched off here: a scroll begins with a pointerdown on whatever row sits
 * under the thumb, so flicking a list buzzed the whole way down. A tap is only
 * a tap in hindsight - you know at pointerUP, once the finger has lifted
 * without travelling.
 *
 * The editor surface is deliberately NOT in `TAPPABLE`. CodeMirror's content is
 * `contenteditable`, and tapping into text to place a caret is navigation
 * rather than actuation; the editor speaks through `feel.ts` when something
 * actually happens to the document. Touch only - a mouse has no motor.
 *
 * Returns its own cleanup.
 */
export function installTapHaptics(): () => void {
  if (!isNativeMobile) {
    return () => {
      // Nothing was installed, so there is nothing to take down. The caller
      // still gets a cleanup so it can treat every platform the same.
    };
  }
  let startX = 0;
  let startY = 0;
  let startAt = 0;
  let armed = false;

  const onDown = (e: PointerEvent) => {
    if (e.pointerType === 'mouse') return;
    armed = e.target instanceof Element && e.target.closest(TAPPABLE) !== null;
    startX = e.clientX;
    startY = e.clientY;
    startAt = e.timeStamp;
  };
  const onUp = (e: PointerEvent) => {
    if (!armed) return;
    armed = false;
    if (e.pointerType === 'mouse') return;
    if (Math.abs(e.clientX - startX) > TAP_SLOP_PX) return;
    if (Math.abs(e.clientY - startY) > TAP_SLOP_PX) return;
    if (e.timeStamp - startAt > TAP_MAX_MS) return;
    // The finger has to still be ON something tappable: a press that began on a
    // row and lifted over the page is a cancelled tap, not a quiet one.
    if (!(e.target instanceof Element) || !e.target.closest(TAPPABLE)) return;
    fireNativeHaptic('selection');
  };
  const onCancel = () => {
    armed = false;
  };

  // Capture, so a handler that stops propagation cannot silence the hand.
  window.addEventListener('pointerdown', onDown, { capture: true, passive: true });
  window.addEventListener('pointerup', onUp, { capture: true, passive: true });
  window.addEventListener('pointercancel', onCancel, { capture: true, passive: true });
  return () => {
    window.removeEventListener('pointerdown', onDown, { capture: true });
    window.removeEventListener('pointerup', onUp, { capture: true });
    window.removeEventListener('pointercancel', onCancel, { capture: true });
  };
}

// --- the preference -------------------------------------------------------

const PREF_KEY = 'glyph-haptics';
const listeners = new Set<() => void>();

/** On by default anywhere there is a motor to feel; a stored choice wins. */
export function hapticsPref(): boolean {
  try {
    const stored = localStorage.getItem(PREF_KEY);
    if (stored === 'on') return true;
    if (stored === 'off') return false;
  } catch {
    // Fall through to the default.
  }
  return isNativeMobile;
}

export function setHapticsPref(on: boolean): void {
  try {
    localStorage.setItem(PREF_KEY, on ? 'on' : 'off');
  } catch {
    // The choice still applies for this run.
  }
  for (const l of listeners) l();
}

/** The switch's state, live across every component that shows it. */
export function useHapticsPref(): boolean {
  return useSyncExternalStore(
    (cb) => {
      listeners.add(cb);
      return () => listeners.delete(cb);
    },
    hapticsPref,
    () => false,
  );
}
